using AslHelp.WikiGen.Api;
using AslHelp.WikiGen.Docfx;
using AslHelp.WikiGen.Reflect;
using AslHelp.WikiGen.Render;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace AslHelp.WikiGen;

/// <summary>
///     Generates the wiki: loads the docfx model, merges in reflected extension members, and renders
///     pages into nested assembly/namespace/type folders (with flat, unique page basenames).
/// </summary>
internal sealed class WikiGenerator(GeneratorOptions options)
{
    // Wraps the auto-generated API navigation embedded in otherwise hand-authored pages
    // (Home, _Sidebar). Only the content between these markers is rewritten on each run.
    // Plain tags rather than HTML comments: markdown renderers strip the unknown tags (keeping
    // the inner content), and the blank lines added around them keep the wrapped markdown rendering.
    private const string RegionBegin = "<auto-generated>";
    private const string RegionEnd = "</auto-generated>";

    public void Run()
    {
        var model = DocfxLoader.Load(options.MetadataDir);
        var summaries = new XmlSummaries(options.XmlPaths);
        var types = ApiModelBuilder.Build(model, options.AssemblyPaths, summaries, options.RepoDir);

        CleanGeneratedFolders();

        var memberPages = 0;
        foreach (var type in types)
        {
            Write(type.File, Pages.Type(type));

            foreach (var overloads in type.Members.GroupBy(m => m.Ref))
            {
                Write(overloads.First().File, Pages.Member(type, [.. overloads]));
                memberPages++;
            }
        }

        foreach (var ns in types.GroupBy(t => (t.Assembly, t.Namespace)))
        {
            var file = $"{ns.Key.Assembly}/{ns.Key.Namespace}/{ns.Key.Namespace}";
            Write(file, Pages.Namespace(ns.Key.Namespace, [.. ns]));
        }

        // The API Reference hub is a pure generated index — always rewritten in full.
        Write(WikiConventions.HubSlug, Pages.Hub(types));

        // Home and _Sidebar interleave generated API navigation with hand-authored prose and
        // tutorial links, so only the marked region is regenerated; the rest is preserved.
        WriteGeneratedRegion("Home", Pages.HomeScaffold(options.AssemblyName), Pages.HomeApi(types));
        WriteGeneratedRegion("_Sidebar", SidebarBuilder.Scaffold(), SidebarBuilder.Build(types, options.Sidebar));

        var namespaces = types.Select(t => t.Namespace).Distinct().Count();
        Console.WriteLine($"WikiGen: {types.Count} types ({memberPages} member pages), {namespaces} namespaces -> {options.OutputDir}");
    }

    // The per-assembly folders are owned entirely by the generator, so wipe them before writing:
    // pages for types/members removed since the last run must not linger. Everything else in the
    // wiki (tutorials, hand-authored pages) lives outside these folders and is left untouched.
    private void CleanGeneratedFolders()
    {
        foreach (var assemblyPath in options.AssemblyPaths)
        {
            var dir = Path.Combine(options.OutputDir, Path.GetFileNameWithoutExtension(assemblyPath));
            if (Directory.Exists(dir))
            {
                Directory.Delete(dir, recursive: true);
            }
        }
    }

    private void Write(string pagePath, string content)
    {
        var full = Path.Combine(options.OutputDir, pagePath + ".md");
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, content);
    }

    // Writes <paramref name="generated"/> into the marked region of a page, preserving everything
    // outside the markers so hand-authored content survives regeneration. On first run the page is
    // created from <paramref name="scaffold"/>; an existing page that lacks markers keeps its content
    // and gets the generated region appended once (subsequent runs then splice in place).
    private void WriteGeneratedRegion(string pagePath, string scaffold, string generated)
    {
        var full = Path.Combine(options.OutputDir, pagePath + ".md");
        var block = $"{RegionBegin}\n\n{generated.TrimEnd()}\n\n{RegionEnd}";

        if (File.Exists(full))
        {
            var existing = File.ReadAllText(full);
            var begin = existing.IndexOf(RegionBegin, StringComparison.Ordinal);
            var end = existing.IndexOf(RegionEnd, StringComparison.Ordinal);

            var merged = begin >= 0 && end > begin
                ? existing[..begin] + block + existing[(end + RegionEnd.Length)..]
                : existing.TrimEnd() + "\n\n" + block + "\n";

            File.WriteAllText(full, merged);
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, scaffold + block + "\n");
    }
}
