<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SrcPath)/core/AslHelp/AslHelp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" />
  </ItemGroup>

</Project>
