<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SrcPath)/core/AslHelp/AslHelp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" PrivateAssets="all" />
  </ItemGroup>

</Project>
